name: Lint YAML files

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '.yamllint'
      - '.github/workflows/yamllint.yml'
  workflow_dispatch:

env:
  LANG: C
  LC_TIME: C
  TZ: Asia/Tokyo

jobs:
  yamllint:
    if: vars.YAMLLINT_ENABLED != 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1.21
